"""empty message

Revision ID: f908050aeb39
Revises: 3993af65c3e6
Create Date: 2019-10-18 22:29:19.021092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f908050aeb39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('city_name', sa.String(length=60), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('temperature', sa.Float(asdecimal=True), nullable=True),
    sa.Column('unit', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperatures')
    # ### end Alembic commands ###
